apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-container
        image: accountnumber.dkr.ecr.ap-south-1.amazonaws.com/ncloudds:latest
        ports:
        - containerPort: 5000
