version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image....       
      - docker build -t test:4 .
      - docker tag test:4 299292937090.dkr.ecr.us-east-1.amazonaws.com/test:4   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image.....
      - docker push 299292937090.dkr.ecr.us-east-1.amazonaws.com/test:4
  artifacts:
  files:
    - '**/*'
  base-directory: base_dir
  name: test
  discard-paths: no
