version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 299292937090.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image..          
      - docker build -t test:4 .
      - docker tag test:$IMAGE_TAG 299292937090.dkr.ecr.us-east-1.amazonaws.com/test:4   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 299292937090.dkr.ecr.us-east-1.amazonaws.com/test:latest:4
